definitions:
  controllers.CreateProductPayload:
    properties:
      description:
        type: string
      image:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  controllers.LoginUserPayload:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  controllers.RegisterUserPayload:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
  models.ProductSchema:
    description: Product details
    properties:
      createdAt:
        description: |-
          CreatedAt represents the timestamp when the product was added
          @json createdAt
          @example "2024-03-19T12:00:00Z"
        example: "2024-03-19T12:00:00Z"
        type: string
      description:
        description: |-
          Description provides details about the product
          @json description
          @example "High-quality wireless headphones with noise cancellation."
        example: High-quality wireless headphones with noise cancellation.
        type: string
      id:
        description: |-
          ID is the unique identifier for the product
          @json id
          @example 1
        example: 1
        type: integer
      image:
        description: |-
          Image is the URL to the product image
          @json image
          @example "https://example.com/images/headphones.jpg"
        example: https://example.com/images/headphones.jpg
        type: string
      name:
        description: |-
          Name of the product
          @json name
          @example "Wireless Headphones"
        example: Wireless Headphones
        type: string
      price:
        description: |-
          Price of the product
          @json price
          @example 99.99
        example: 99.99
        type: number
      quantity:
        description: |-
          Quantity available in stock
          @json quantity
          @example 50
        example: 50
        type: integer
      updatedAt:
        description: |-
          UpdatedAt represents the last updated timestamp of the product
          @json updatedAt
          @example "2024-03-19T12:30:00Z"
        example: "2024-03-19T12:30:00Z"
        type: string
    type: object
info:
  contact: {}
  description: This is E-Commerce API server
  termsOfService: http://github.com/ZUBERKHAN034/go-ecom
  title: E-Commerce API
  version: "1.0"
paths:
  /product:
    post:
      consumes:
      - application/json
      description: Create Product
      parameters:
      - description: Product Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateProductPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Product created successfully
          schema:
            type: string
        "400":
          description: Product already exists
          schema:
            type: string
      summary: Create Product
      tags:
      - Product
  /products:
    get:
      consumes:
      - application/json
      description: Get Products
      produces:
      - application/json
      responses:
        "200":
          description: List of products
          schema:
            items:
              $ref: '#/definitions/models.ProductSchema'
            type: array
      summary: Get Products
      tags:
      - Product
  /user/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: User Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginUserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: User logged in successfully
          schema:
            type: string
        "400":
          description: Invalid password
          schema:
            type: string
      summary: Login
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: User Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterUserPayload'
      produces:
      - application/json
      responses:
        "201":
          description: User Registered successfully
          schema:
            type: string
        "400":
          description: User already exists
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Register
      tags:
      - User
swagger: "2.0"
